from __future__ import annotations

import csv
import json
from pathlib import Path


ROOT = Path(r"E:\Projects\RL-LAM-ScanOpt")
BATCH = "stage3_true_variable_N_probe60_v01"

CANDIDATE_CSV = ROOT / "outputs" / "stage3_run_06_variable_n_probe60_candidate_order_generation" / "variable_N_probe60_candidate_orders.csv"

OUT_ROOT = ROOT / "cae_model" / BATCH
HANDOFF_ROOT = ROOT / "outputs" / "stage3_manual_probe60_handoff"
HANDOFF_ROOT.mkdir(parents=True, exist_ok=True)

COMMAND_FILE = HANDOFF_ROOT / "variable_N_probe60_abqjobpilot_commands_FIXED.txt"
CASE_MANIFEST = HANDOFF_ROOT / "variable_N_probe60_case_manifest_FIXED.csv"


def read_order_rows(path: Path) -> list[dict]:
    if not path.exists():
        raise FileNotFoundError(f"Candidate order CSV not found: {path}")

    rows = []
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)
    return rows


def parse_order_json(raw: str) -> list[int]:
    try:
        order = json.loads(raw)
    except Exception as exc:
        raise ValueError(f"Cannot parse order_json: {raw[:120]}") from exc

    if not isinstance(order, list):
        raise ValueError("order_json is not a list")

    return [int(x) for x in order]


def validate_order(n: int, order: list[int]) -> None:
    expected = set(range(n))
    actual = set(order)

    if len(order) != n:
        raise ValueError(f"Wrong order length for N={n}: {len(order)}")
    if actual != expected:
        raise ValueError(f"Illegal order for N={n}: missing={sorted(expected-actual)}, extra={sorted(actual-expected)}")
    if len(order) != len(actual):
        raise ValueError(f"Duplicate tracks for N={n}: {order}")


def main() -> None:
    rows = read_order_rows(CANDIDATE_CSV)

    manifest_rows = []
    commands = []

    for row in rows:
        n = int(row["n"])
        strategy_name = row["strategy_name"]

        # Expected strategy name already like:
        # N12_A01_raster_left_to_right
        if not strategy_name.startswith(f"N{n}_"):
            strategy_name = f"N{n}_{strategy_name}"

        order = parse_order_json(row["order_json"])
        validate_order(n, order)

        case_dir = OUT_ROOT / f"N{n}" / strategy_name
        case_dir.mkdir(parents=True, exist_ok=True)

        job_name = f"J2D_N{n}_{strategy_name}"
        expected_cae = case_dir / f"{job_name}.cae"
        expected_inp = case_dir / f"{job_name}.inp"
        expected_jnl = case_dir / f"{job_name}.jnl"
        scan_json = case_dir / f"scan_order_{strategy_name}.json"

        with scan_json.open("w", encoding="utf-8") as f:
            json.dump(
                {
                    "batch": BATCH,
                    "n": n,
                    "strategy_name": strategy_name,
                    "job_name": job_name,
                    "scan_order": order,
                    "expected_cae": str(expected_cae),
                    "expected_inp": str(expected_inp),
                    "expected_jnl": str(expected_jnl),
                    "teacher_validated": False,
                    "notes": "Case metadata only. CAE/INP/JNL not generated by this script.",
                },
                f,
                indent=2,
            )

        commands.append(
            f'enqueue --inp "{expected_inp}" --cpus 14 --batch {BATCH} --strategy {strategy_name}'
        )

        manifest_rows.append(
            {
                "n": n,
                "strategy_name": strategy_name,
                "job_name": job_name,
                "case_dir": str(case_dir),
                "scan_order_json": str(scan_json),
                "expected_cae": str(expected_cae),
                "expected_inp": str(expected_inp),
                "expected_jnl": str(expected_jnl),
                "inp_exists_now": expected_inp.exists(),
            }
        )

    with COMMAND_FILE.open("w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(commands) + "\n")

    with CASE_MANIFEST.open("w", encoding="utf-8-sig", newline="") as f:
        fieldnames = [
            "n",
            "strategy_name",
            "job_name",
            "case_dir",
            "scan_order_json",
            "expected_cae",
            "expected_inp",
            "expected_jnl",
            "inp_exists_now",
        ]
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(manifest_rows)

    print(f"Created case directories: {len(manifest_rows)}")
    print(f"Wrote manifest: {CASE_MANIFEST}")
    print(f"Wrote abqjobpilot commands: {COMMAND_FILE}")

    bad_paths = [cmd for cmd in commands if "\\N12N12_" in cmd or "\\N16N16_" in cmd or "\\N24N24_" in cmd or "\\N40N40_" in cmd]
    if bad_paths:
        raise RuntimeError("Bad NxxNxx path still exists")

    print("Path schema check: PASS")
    print("Note: INP files are still not generated. Do not enqueue until INP files exist.")


if __name__ == "__main__":
    main()